"""remove price from hotels

Revision ID: 1d031192f9e4
Revises: 8dd7baa6bb1b
Create Date: 2026-06-19 12:17:59.541691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d031192f9e4'
down_revision: Union[str, Sequence[str], None] = '8dd7baa6bb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('price', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
