"""add booking status to bookings

Revision ID: 2130633b7492
Revises: b3cbbc09b6dd
Create Date: 2026-06-22 07:57:08.435103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2130633b7492'
down_revision: Union[str, Sequence[str], None] = 'b3cbbc09b6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_status', sa.String(length=20), nullable=False, server_default='confirmed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'booking_status')
    # ### end Alembic commands ###
