"""add experiences table

Revision ID: 49205fac1d20
Revises: 167861b13ecf
Create Date: 2026-07-06 14:14:36.681326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49205fac1d20'
down_revision: Union[str, Sequence[str], None] = '167861b13ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price_per_person', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_price_per_person'), ['price_per_person'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiences_title'), ['title'], unique=False)

    # with op.batch_alter_table('bookings', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # with op.batch_alter_table('hotels', schema=None) as batch_op:
    #     batch_op.create_foreign_key(None, 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('hotels', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    # with op.batch_alter_table('bookings', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiences_title'))
        batch_op.drop_index(batch_op.f('ix_experiences_price_per_person'))
        batch_op.drop_index(batch_op.f('ix_experiences_location'))
        batch_op.drop_index(batch_op.f('ix_experiences_id'))

    op.drop_table('experiences')
    # ### end Alembic commands ###
