"""Add is_host to users and owner_id to hotels

Revision ID: 5b208589417a
Revises: d142cb5a14ca
Create Date: 2026-07-01 14:30:42.726793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b208589417a'
down_revision: Union[str, Sequence[str], None] = 'd142cb5a14ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_host', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_host', sa.Boolean(), nullable=False, server_default='0'))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_host')
    # ### end Alembic commands ###
