"""add price fields to bookings

Revision ID: 5d2793bfb1ee
Revises: ee69a36379b3
Create Date: 2026-06-19 10:34:47.253971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2793bfb1ee'
down_revision: Union[str, Sequence[str], None] = 'ee69a36379b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('number_of_nights', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('price_per_night', sa.Integer(), nullable=False))
    op.add_column('bookings', sa.Column('total_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'total_price')
    op.drop_column('bookings', 'price_per_night')
    op.drop_column('bookings', 'number_of_nights')
    # ### end Alembic commands ###
