"""add hotel amenities

Revision ID: 6c518b39c11e
Revises: b812daba8a30
Create Date: 2026-08-04 20:35:32.800867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6c518b39c11e"
down_revision: Union[str, Sequence[str], None] = "b812daba8a30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("hotels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "has_gym", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "accessibility_features",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_balcony", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "free_wifi", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_cribs", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "pet_friendly", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "smoke_free", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_pool", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_laundry", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "free_breakfast",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_parking", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "air_conditioned",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_kitchen", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "has_spa", sa.Boolean(), nullable=False, server_default=sa.false()
            )
        )
        batch_op.add_column(
            sa.Column(
                "airport_shuttle",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hotels", schema=None) as batch_op:
        batch_op.drop_column("airport_shuttle")
        batch_op.drop_column("has_spa")
        batch_op.drop_column("has_kitchen")
        batch_op.drop_column("air_conditioned")
        batch_op.drop_column("has_parking")
        batch_op.drop_column("free_breakfast")
        batch_op.drop_column("has_laundry")
        batch_op.drop_column("has_pool")
        batch_op.drop_column("smoke_free")
        batch_op.drop_column("pet_friendly")
        batch_op.drop_column("has_cribs")
        batch_op.drop_column("free_wifi")
        batch_op.drop_column("has_balcony")
        batch_op.drop_column("accessibility_features")
        batch_op.drop_column("has_gym")

    # ### end Alembic commands ###
