"""add total_price to experience requests

Revision ID: 81574ea98949
Revises: cdd0f643fa5b
Create Date: 2026-07-08 10:18:02.473491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81574ea98949'
down_revision: Union[str, Sequence[str], None] = 'cdd0f643fa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience_requests', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
