"""add embedding column to reviews

Revision ID: 99f23f1294b8
Revises: 6c518b39c11e
Create Date: 2026-08-05 15:04:48.038218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "99f23f1294b8"
down_revision: Union[str, Sequence[str], None] = "6c518b39c11e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("embedding")

    # ### end Alembic commands ###
