"""add total inventory to rooms

Revision ID: b3cbbc09b6dd
Revises: 1d031192f9e4
Create Date: 2026-06-21 09:25:07.051554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cbbc09b6dd'
down_revision: Union[str, Sequence[str], None] = '1d031192f9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('total_inventory', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'total_inventory')
    # ### end Alembic commands ###
