"""remove metro_area from hotels

Revision ID: b812daba8a30
Revises: 30ebc38268d7
Create Date: 2026-07-26 17:08:31.208983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b812daba8a30'
down_revision: Union[str, Sequence[str], None] = '30ebc38268d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_column('metro_area')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metro_area', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
