"""add city to hotels

Revision ID: fd9cb06eeeb4
Revises: 1e3f64da9e00
Create Date: 2026-06-16 13:50:56.777526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9cb06eeeb4'
down_revision: Union[str, Sequence[str], None] = '1e3f64da9e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('city', sa.String(), nullable=False, server_default='Unknown'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'city')
    # ### end Alembic commands ###
